language: python
python:
  - "3.6"
addons:
  apt:
    packages:
      - openjdk-8-jdk
install:
  - pip install pylint==2.4
  - pylint --version
  - |
      export ECLIPSE_TAR=$TRAVIS_BUILD_DIR/../eclipse.tar.gz
      wget https://archive.eclipse.org/eclipse/downloads/drops4/R-4.5.2-201602121500/eclipse-SDK-4.5.2-linux-gtk-x86_64.tar.gz -O $ECLIPSE_TAR
      tar -C $TRAVIS_BUILD_DIR/.. -xf $ECLIPSE_TAR
      export ECLIPSE_EXE=$TRAVIS_BUILD_DIR/../eclipse/eclipse
      export JDT=$TRAVIS_BUILD_DIR/ecj.jar
      wget https://www.eclipse.org/downloads/download.php?file=/eclipse/downloads/drops4/R-4.5.2-201602121500/ecj-4.5.2.jar -O $JDT
script: ./mx --strict-compliance gate --strict-mode
