language: python
python:
  - "2.7"
addons:
  apt:
    packages:
      - oracle-java8-installer
install:
  - pip install astroid==1.1.0
  - pip install pylint==1.1.0
  - pylint --version
  - |
      export ECLIPSE_TAR=$TRAVIS_BUILD_DIR/../eclipse.tar.gz
      wget https://lafo.ssw.uni-linz.ac.at/slavefiles/gate/eclipse-jdk8-linux-x86_64.tar.gz -O $ECLIPSE_TAR
      tar -C $TRAVIS_BUILD_DIR/.. -xf $ECLIPSE_TAR
      export ECLIPSE_EXE=$TRAVIS_BUILD_DIR/../eclipse/eclipse
      export JDT=$TRAVIS_BUILD_DIR/ecj.jar
      wget http://ftp.halifax.rwth-aachen.de/eclipse/eclipse/downloads/drops4/R-4.5.2-201602121500/ecj-4.5.2.jar -O $JDT
script: ./mx --strict-compliance gate --strict-mode
