on: [push, pull_request]

env:
  JDT: ${{ github.workspace }}/ecj.jar
  ECLIPSE_TAR: ${{ github.workspace }}/../eclipse.tar.gz
  ECLIPSE_EXE: ${{ github.workspace }}/../eclipse/eclipse

jobs:
  gate:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ '3.8' ]
    name: Python ${{ matrix.python-version }} gate
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - uses: actions/setup-java@v1
        with:
            java-version: 17
      - name: Style dependencies
        run: |
          cat common.json |
            jq -r '.deps.common.packages | to_entries[] | select(.key | startswith("pip:")) | (.key | split(":")[1]) + .value' |
            xargs pip install
      - run: pylint --version
      - name: Download and set up dependencies
        run: |
          wget https://archive.eclipse.org/eclipse/downloads/drops4/R-4.5.2-201602121500/eclipse-SDK-4.5.2-linux-gtk-x86_64.tar.gz -O $ECLIPSE_TAR
          tar -C ${{ github.workspace }}/.. -xf $ECLIPSE_TAR
          wget https://www.eclipse.org/downloads/download.php?file=/eclipse/downloads/drops4/R-4.5.2-201602121500/ecj-4.5.2.jar -O $JDT
      - name: mx gate
        run: ./mx --strict-compliance gate --strict-mode
      - name: Test native build without vcs dir
        run: |
          rm -rf .git
          ./mx -V build --projects com.oracle.jvmtiasmagent
